# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9350035ff493d34ac129e86a6579a858dac4adf42dcecb90746012e9561597364c9d4317ccbb8233ee204512e007a7a8b1cbcb8941719e3c8b25bc1f4b44d8bc

test:
  secret_key_base: b47e9355ca8c98da86a36f9da8590c29863b5aca2b7d56f6bdb66583c810d9762ad595c950cebf2f61fb3da7ac9ab16eb5850d2d5c0f4a0a03e85eb453605e71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
